name: Deploy to google cloud
on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Install gcloud components
        run: sudo apt-get install google-cloud-sdk-app-engine-java
     
      - name: Setting account
        run: gcloud config set account github@liferay-sopapo.iam.gserviceaccount.com
     
      - name: Setting project
        run: gcloud config set project liferay-sopapo
     
      - name: Activate service account
        env:
          GCLOUD_GITKEY: ${{ secrets.GCLOUD_GITKEY }}
        run: echo $GCLOUD_GITKEY > gcloudkey.js && gcloud auth activate-service-account github@liferay-sopapo.iam.gserviceaccount.com --key-file gcloudkey.js
 
      - name: Build with Gradle
        env:
           SOPAPO_FIXPACKS_BASE_URL: ${{ secrets. SOPAPO_FIXPACKS_BASE_URL }}
           SOPAPO_LIFERAY_AUTH_URL: ${{ secrets. SOPAPO_LIFERAY_AUTH_URL }}
        run: mkdir -p src/main/resources/ && echo -e "$SOPAPO_LIFERAY_AUTH_URL\n$SOPAPO_FIXPACKS_BASE_URL" > src/main/resources/application.properties && ./gradlew appengineDeploy
        
